export default {
  "body":{
     "eid":"root",
     "type":"body",
     "children":[
        {
           "eid":"HJVcKZ4ps",
           "type":"fullwidth",
           "children":[
            {
              "eid":"KdRj3P5VJzc",
              "type":"text",
              "attrs":{
                 "text":"<p style=\"text-align: center;\"><strong>The edge is a ghost.</strong></p>\n"
              },
              "style":{
                 "padding-left":"10px",
                 "padding-bottom":"0px",
                 "padding-right":"10px",
                 "padding-top":"5px",
                 "a":{
                    "text-decoration":"none",
                    "color":"#a7a7a7"
                 },
                 "line-height":"55px",
                 "color":"#ffffff",
                 "font-size":"45px",
                 "font-family":"Helvetica Neue, Helvetica, Arial, Verdana, sans-serif",
                 "h6":{
                    "line-height":"16px",
                    "color":"#000000",
                    "font-size":"16px",
                    "font-family":"arial"
                 },
                 "h5":{
                    "line-height":"18px",
                    "color":"#000000",
                    "font-size":"18px",
                    "font-family":"arial"
                 },
                 "h4":{
                    "line-height":"20px",
                    "color":"#000000",
                    "font-size":"20px",
                    "font-family":"arial"
                 },
                 "h3":{
                    "line-height":"22px",
                    "color":"#ffffff",
                    "font-size":"22px",
                    "font-family":"arial",
                    "letter-spacing":"normal"
                 },
                 "h2":{
                    "line-height":"26px",
                    "color":"#ffffff",
                    "font-size":"26px",
                    "font-family":"arial",
                    "letter-spacing":"normal"
                 },
                 "h1":{
                    "line-height":"32px",
                    "color":"#ffffff",
                    "font-size":"32px",
                    "font-family":"arial",
                    "letter-spacing":"normal"
                 },
                 "letter-spacing":"normal"
              },
              "customData":null
           }
           ],
           "attrs":{
              "hideOnMobile":false,
              "hideOnDesktop":false,
              "lock":false,
              "marker":""
           },
           "style":{
              "background-color":"",
              "background-position":"center center",
              "background-repeat":"no-repeat",
              "background-image":"url()",
              "body-width":600,
              "content-width":600,
              "content-background-color":"#5C9AEB",
              "content-background-repeat":"no-repeat",
              "content-background-position":"center center",
              "content-background-image":"url()",
              "content-margin-left":"0px",
              "content-margin-bottom":"0px",
              "content-margin-right":"0px",
              "content-margin-top":"0px",
              "content-padding-left":"10px",
              "content-padding-bottom":"10px",
              "content-padding-right":"10px",
              "content-padding-top":"10px",
              "content-border-radius":"0px",
              "content-border-left":"0px solid #000000",
              "content-border-bottom":"0px solid #000000",
              "content-border-right":"0px solid #000000",
              "content-border-top":"0px solid #000000"
           },
           "customData":{
              
           }
        }
     ],
     "attrs":{
        "usedColors":[
           "#595959",
           "#000000",
           "#cccccc",
           "#cc0000",
           "#FCFCFC",
           "#5555ff",
           "#FDFDFD",
           "#FBFBFB",
           "#999999",
           "#f2f2f2",
           "#ffffff"
        ]
     },
     "style":{
        "background-color":"#E4E8F1",
        "background-position":"center",
        "background-repeat":"repeat",
        "body-width":600
     },
     "version":"2.0.0"
  },
  "title":"Business Promo",
  "previewText":"",
  "subjectLine":""
}
